### ISSUE TITLE
Missing IMultiTenant interface on Payment and Refund Entity

### ISSUE THREAD

**Issue by slarkerino** [EasyAbp/PaymentService#63]
Recently using this module with a multi-tenant project I found when I split tenant database, no entries were found in tenant database. It should be caused by Missing IMultiTenant interface on Payment and Refund Entity.

`public class Payment : FullAuditedAggregateRoot<Guid>, IPayment`

**Comment by gdlcf88** [comment]
Thanks for reporting. Can you help to fix it and create a PR?

**Comment by slarkerino** [comment]
> Thanks for reporting. Can you help to fix it and create a PR?

ok

**Comment by slarkerino** [comment]
#64

**Comment by gdlcf88** [comment]
It's included in `2.7.0-preview.2`.
